custom_cursor_colors: true

# Font configuration
font:
  # Point size
  size: 9.0
  normal:
    family: Noto Sans Mono
    style: Regular

window:
  opacity: 0.9
  padding:
    x: 5
    y: 5

# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: "0x0f1419"
    foreground: "0xe6e1cf"

  # Normal colors
  normal:
    black: "0x000000"
    red: "0xf34a4a"
    green: "0xbae67e"
    yellow: "0xffee99"
    blue: "0x73d0ff"
    magenta: "0xd4bfff"
    cyan: "0x83CEC6"
    white: "0xf2f2f2"

  # Bright colors
  bright:
    black: "0x737d87"
    red: "0xff3333"
    green: "0xc2d94c"
    yellow: "0xe7c547"
    blue: "0x59c2ff"
    magenta: "0xb77ee0"
    cyan: "0x5ccfe6"
    white: "0xffffff"

key_bindings:
  - { key: Back, mods: Control, chars: "\x1b\x7f" }
