# Default colors
[colors.primary]
background = '#000000'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black   = '#AF5F5F'
red     = '#FF5F5F'
green   = '#5FAF5F'
yellow  = '#AF875F'
blue    = '#5F87AF'
magenta = '#D787D7'
cyan    = '#5FAFAF'
white   = '#C6C6C6'

# Bright colors
[colors.bright]
black   = '#282828'
red     = '#FF5F5F'
green   = '#5FD75F'
yellow  = '#FFD787'
blue    = '#5FAFFF'
magenta = '#FF87FF'
cyan    = '#5FD7D7'
white   = '#FFFFFF'

[font]
size = 9.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Control"

[window]
opacity = 0.85

[window.padding]
x = 5
y = 5
